---
- hosts: guests:extras
#- hosts: extras
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
    # ruby
    - command: /home/isucon/.xbuild/ruby-install 2.7.3 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby
    - command: /.local/ruby/bin/gem install bundler
      args:
        creates: /home/isucon/.local/ruby/bin/bundle
    # node
    - command: /home/isucon/.xbuild/node-install v4.4.3 /home/isucon/.local/node
      args:
        creates: /home/isucon/.local/node/bin/node
      tags:
        - nodejs
    # golang
    - command: /home/isucon/.xbuild/go-install 1.16.3 /home/isucon/.local/go
      args:
        creates: /home/isucon/.local/go/bin/go

- hosts: guests:extras
  become: yes
  gather_facts: no
  tasks:
    - name: Apt update
      apt: update_cache=yes
      tags: php7
    - name: PHP7 install
      apt: name="{{item}}"
      with_items:
        - php7.4-cli
        - php7.4-fpm
        - php7.4-mysql
        - php-memcached
      tags: php7
    - name: copy www.conf (php-fpm)
      copy: src=../files/etc/php/7.4/fpm/pool.d/www.conf dest=/etc/php/7.4/fpm/pool.d/www.conf owner=root mode=644
    - name: stop php-fpm
      service: name=php7.4-fpm state=stopped enabled=yes
